// <auto-generated />
namespace Mvc_Project_Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addstudentmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstudentmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202601300714121_addstudentmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
